apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
spec:
  description: ArgoCD App Project
  sourceRepos:
  - 'git@github.com:niklasfrick/homelab.git'
  - 'git@github.com:niklasfrick/app-settings.git'
  - 'https://argoproj.github.io/argo-helm'
  destinations:
  - namespace: 'argocd'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true
