provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token

policy: sync
txtOwnerId: external-dns-external-gateway

annotationFilter: "external-dns.alpha.kubernetes.io/enabled=true"

gatewayNamespace: external-gateway

sources:
  - gateway-httproute

serviceMonitor:
  enabled: true

extraArgs:
  - --cloudflare-proxied
  - --cloudflare-record-comment="provisioned by external-dns"
