loki:
  commonConfig:
    replication_factor: 1
  storage_config:
    aws:
      region: bal
      bucketnames: zendo-loki-chunk
      s3forcepathstyle: true
  storage:
    type: s3
    bucketNames:
      chunks: zendo-loki-chunk
      ruler: zendo-loki-ruler
      admin: zendo-loki-admin
    s3:
      endpoint: s3.bal.949x.net:9001
      region: bal
      secretAccessKey: ${S3_SECRET_KEY}
      accessKeyId: ${S3_ACCESS_KEY}
      s3ForcePathStyle: true
      insecure: false

gateway:
  service:
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: 10.96.211.102
    labels:
      cilium-lb-ip-pool: internal-lb-ip-pool
