instance: zendo
grafana:
  version: 12.3.1 # renovate:docker depName=grafana registryUrl=registry-1.docker.io/grafana
  datasource:
    - prometheus:
      name: prometheus
      type: prometheus
      url: http://thanos-query-frontend.thanos.svc.cluster.local:9090
      isDefault: true
      jsonData:
        prometheusType: Prometheus
        prometheusVersion: 3.9.1
        incrementalQuerying: true
    - loki:
      name: loki
      type: loki
      url: http://loki-gateway.loki.svc.cluster.local
      jsonData:
        manageAlerts: true # Disables/uncheck 'Manage alerts via Alerting UI'
    - tempo:
      name: tempo
      type: tempo
      url: http://tempo.tempo.svc.cluster.local:3200
  hostname: grafana.apps.949x.net
  route:
    enabled: true
  storage:
    storageClassName: ceph-block
