{{- $applicationName := "alloy" }}
{{- if hasKey .Values.apps $applicationName }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $applicationName }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $applicationName }}
  sources:
  - chart: alloy
    repoURL: https://grafana.github.io/helm-charts
    path: grafana
    targetRevision: {{ index .Values.apps $applicationName "targetRevision" }}
    helm:
      releaseName: alloy
      valueFiles:
      - $values/apps/{{ $applicationName }}/settings/global-{{ $applicationName }}-helm-values.yaml
      - $values/apps/{{ $applicationName }}/settings/{{ .Values.instance }}/{{ .Values.instance }}-{{ $applicationName }}-helm-values.yaml
  {{- if index .Values.apps $applicationName "configHelmChart" "enabled" }}
  - repoURL: git@github.com:niklasfrick/homelab.git
    path: apps/{{ $applicationName }}/helm/{{ $applicationName }}-config
    helm:
      releaseName: {{ $applicationName }}-config
      valueFiles:
        - $values/apps/{{ $applicationName }}/settings/{{ .Values.instance }}/{{ .Values.instance }}-{{ $applicationName }}-config-helm-values.yaml
  {{- end }}
  - repoURL: git@github.com:niklasfrick/homelab.git
    ref: values
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/warn-version: latest
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
