bgp:
  routerIpV4Address: 10.96.10.1

internalLbIpPool:
  enabled: true
  name: internal-lb-ip-pool
  ipV4Pool:
    start: 10.96.210.100
    stop: 10.96.210.150

externalLbIpPool:
  enabled: false
  name: external-lb-ip-pool
  ipV4Pool:
    start: 10.96.210.200
    stop: 10.96.210.250

internalGateway:
  enabled: true
  name: internal-gateway
  namespace: kube-system
  ipV4: 10.96.210.100
  domain: "*.apps-omni.949x.net"
  tlsSecretName: "apps-omni-949x-net-tls"

externalGateway:
  enabled: false
  name: external-gateway
  namespace: external-gateway
  ipV4: 10.96.210.200
  domain: "*.ext.949x.net"
  tlsSecretName: "ext-949x-net-tls"
  extraAnnotations: {}
