configuration:
  features: EnableCSI
  backupStorageLocation:
    - name: nas-bal
      provider: aws
      default: true
      bucket: zendo-velero-backup
      config:
        s3Url: https://s3.bal.949x.net:9001
        publicUrl: https://s3.bal.949x.net:9001
        insecureSkipTLSVerify: false
        region: bal
        s3ForcePathStyle: true
  volumeSnapshotLocation:
    - name: rook-ceph
      provider: csi
      default: true
  defaultVolumeSnapshotLocations: csi:rook-ceph
