apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-aistor-s3-bal-keys
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-secret-store
    kind: ClusterSecretStore
  target:
    name: minio-aistor-s3-bal-keys
  data:
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: /minio-aistor-s3-bal/GLOBAL_RW_ACCESS_KEY
        conversionStrategy: Default # ArgoCD out of Sync Fix
        decodingStrategy: None # ArgoCD out of Sync Fix
        metadataPolicy: None # ArgoCD out of Sync Fix
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: /minio-aistor-s3-bal/GLOBAL_RW_SECRET_KEY
        conversionStrategy: Default # ArgoCD out of Sync Fix
        decodingStrategy: None # ArgoCD out of Sync Fix
        metadataPolicy: None # ArgoCD out of Sync Fix
