loki:
  commonConfig:
    replication_factor: 1
  storage_config:
    aws:
      region: bal
      bucketnames: omni-local-loki-chunk
      s3forcepathstyle: true
  storage:
    type: s3
    bucketNames:
      chunks: omni-local-loki-chunk
      ruler: omni-local-loki-ruler
      # admin: omni-local-loki-admin
    s3:
      endpoint: s3.bal.949x.net:9000
      region: bal
      secretAccessKey: ${S3_SECRET_KEY}
      accessKeyId: ${S3_ACCESS_KEY}
      s3ForcePathStyle: true
      insecure: false

gateway:
  service:
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: 10.96.210.102
    labels:
      cilium-lb-ip-pool: internal-lb-ip-pool
