bgp:
  routerIpV4Address: 10.96.10.1

internalLbIpPool:
  enabled: true
  name: internal-lb-ip-pool
  ipV4Pool:
    start: 10.96.211.100
    stop: 10.96.211.150

externalLbIpPool:
  enabled: true
  name: external-lb-ip-pool
  ipV4Pool:
    start: 10.96.211.200
    stop: 10.96.211.250

internalGateway:
  enabled: true
  name: internal-gateway
  namespace: kube-system
  ipV4: 10.96.211.100
  domain: "*.apps.949x.net"
  tlsSecretName: "apps-949x-net-tls"

externalGateway:
  enabled: true
  name: external-gateway
  namespace: external-gateway
  ipV4: 10.96.211.200
  domain: "*.949x.net"
  tlsSecretName: "949x-net-tls"
