{{- if .Values.subnetRouter.enabled }}
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: {{ .Values.instance }}-local-networks-subnet-router
spec:
  hostname: {{ .Values.instance }}-local-networks-subnet-router
  subnetRouter:
    advertiseRoutes:
{{- range .Values.subnetRouter.advertiseRoutes }}
      - {{ . | quote }}
{{- end }}
{{- end }}
