apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-secret-store
    kind: ClusterSecretStore
  target:
    name: operator-oauth
  data:
    - secretKey: client_id
      remoteRef:
        key: /tailscale/{{ .Values.tailscaleOperatorSecret.remoteRefKey.clientId }}
    - secretKey: client_secret
      remoteRef:
        key: /tailscale/{{ .Values.tailscaleOperatorSecret.remoteRefKey.clientSecret }}
