{{ if .Values.internalGateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-redirect
  namespace: {{ .Values.internalGateway.namespace }}
spec:
  parentRefs:
  - name: {{ .Values.internalGateway.name }}
    namespace: {{ .Values.internalGateway.namespace }}
    sectionName: http
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
{{- end }}
{{- if .Values.externalGateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-redirect
  namespace: {{ .Values.externalGateway.namespace }}
spec:
  parentRefs:
  - name: {{ .Values.externalGateway.name }}
    namespace: {{ .Values.externalGateway.namespace }}
    sectionName: http
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
{{- end }}
