serviceMonitor:
  enabled: true

extraObjects:
  - apiVersion: external-secrets.io/v1
    kind: ClusterSecretStore
    metadata:
      name: infisical-secret-store
    spec:
      provider:
        infisical:
          auth:
            universalAuthCredentials:
              clientId:
                key: clientId
                namespace: external-secrets
                name: infisical-auth-credentials
              clientSecret:
                key: clientSecret
                namespace: external-secrets
                name: infisical-auth-credentials
          # Details to pull secrets from
          secretsScope:
            projectSlug: homelab
            environmentSlug: prod
            # optional
            secretsPath: / # Root is "/"
            # optional
            recursive: true # Default is false
            # optional
            expandSecretReferences: false # Default is true
          # optional
          hostAPI: https://eu.infisical.com

resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 100Mi

webhook:
  resources:
    limits:
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 100Mi

certController:
  resources:
    limits:
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 100Mi
