alloy:
  enableReporting: false
  resources:
    limits:
      memory: 260Mi
    requests:
      cpu: 13m
      memory: 200Mi

  mounts:
    dockercontainers: true
    varlog: false
    extra:
      - name: taloslogs
        mountPath: /var/log/talos
        readOnly: true

controller:
  tolerations:
    - key: node-role.kubernetes.io/controlplane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

  volumes:
    extra:
      - name: taloslogs
        hostPath:
          path: /var/log
