apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-secret-store
    kind: ClusterSecretStore
  target:
    name: alertmanager-secrets
  data:
    - secretKey: telegram-bot-token
      remoteRef:
        key: /telegram/GLOBAL_ALERTMANAGER_TELEGRAM_BOT_TOKEN
        conversionStrategy: Default # ArgoCD out of Sync Fix
        decodingStrategy: None # ArgoCD out of Sync Fix
        metadataPolicy: None # ArgoCD out of Sync Fix
    - secretKey: healthchecks-io-deadman-url
      remoteRef:
        key: /healthchecks-io/{{ .Values.instance }}/HEALTHCHECKS_IO_DEADMAN_URL
        conversionStrategy: Default # ArgoCD out of Sync Fix
        decodingStrategy: None # ArgoCD out of Sync Fix
        metadataPolicy: None # ArgoCD out of Sync Fix
