{{- if .Values.projects.workloads.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: app-settings-repo
type: Opaque
stringData:
  project: workloads
  url: git@github.com:niklasfrick/app-settings.git
{{- end }}
