apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: bitnami-oci-repo
type: Opaque
stringData:
  project: infra
  url: registry-1.docker.io/bitnamicharts
  type: helm
  enableOCI: "true"
