instance: omni-local
grafana:
  hostname: grafana.omni.apps-omni.949x.net
  ingress:
    enabled: true
    tls:
      clusterIssuer: letsencrypt-prod
      secretName: grafana.omni.apps-omni.949x.net
