apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hf-token-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-secret-store
    kind: ClusterSecretStore
  target:
    name: hf-token
  data:
    - secretKey: HF_TOKEN
      remoteRef:
        key: /vllm/{{ .Values.hfTokenSecret.remoteRefKey }}
