apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vllm-apikey-externalsecret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-secret-store
    kind: ClusterSecretStore
  target:
    name: vllm-apikey
  data:
    - secretKey: VLLM_API_KEY
      remoteRef:
        key: /vllm/{{ .Values.vllmSecrets.vllmApiKey.remoteRefKey }}
