instance: zendo

apps:
  alloy:
    targetRevision: 1.3.1 # renovate:helm depName=alloy registryUrl=https://grafana.github.io/helm-charts
    configHelmChart:
      enabled: false
  argocd:
    targetRevision: 9.0.3 # renovate:helm depName=argo-cd registryUrl=https://argoproj.github.io/argo-helm
    configHelmChart:
      enabled: false
  cert-manager:
    targetRevision: 1.19.1 # renovate:helm depName=cert-manager registryUrl=https://charts.jetstack.io
    configHelmChart:
      enabled: false
  cilium:
    targetRevision: 1.18.3 # renovate:helm depName=cilium registryUrl=https://helm.cilium.io
    configHelmChart:
      enabled: true
  external-secrets:
    targetRevision: 0.20.3 # renovate:helm depName=external-secrets registryUrl=https://charts.external-secrets.io
    configHelmChart:
      enabled: false
  grafana:
    targetRevision: "v5.20.0" # renovate:helm depName=grafana-operator registryUrl=https://grafana.github.io/helm-charts
    configHelmChart:
      enabled: true
  kube-prometheus-stack:
    targetRevision: 78.5.0 # renovate:helm depName=kube-prometheus-stack registryUrl=https://prometheus-community.github.io/helm-charts
    configHelmChart:
      enabled: true
  loki:
    targetRevision: 6.44.0 # renovate:helm depName=loki registryUrl=https://grafana.github.io/helm-charts
    configHelmChart:
      enabled: false
  rook-ceph:
    targetRevision: 1.18.6 # renovate:helm depName=rook-ceph registryUrl=https://charts.rook.io/release
    configHelmChart:
      enabled: false
  rook-ceph-cluster:
    targetRevision: 1.18.6 # renovate:helm depName=rook-ceph-cluster registryUrl=https://charts.rook.io/release
    configHelmChart:
      enabled: true
  thanos:
    targetRevision: 17.3.1 # renovate:helm depName=thanos registryUrl=oci://registry-1.docker.io/bitnamicharts
    configHelmChart:
      enabled: false
  twingate-connector:
    targetRevision: 0.1.31 # renovate:helm depName=connector registryUrl=https://twingate.github.io/helm-charts
    configHelmChart:
      enabled: true
