instance: zendo

projects:
  workloads:
    enabled: true

apps:
  alloy:
    targetRevision: 1.6.0 # renovate:helm depName=alloy registryUrl=https://grafana.github.io/helm-charts
    configHelmChart:
      enabled: false
  argocd:
    targetRevision: 9.1.5 # renovate:helm depName=argo-cd registryUrl=https://argoproj.github.io/argo-helm
    configHelmChart:
      enabled: false
  cert-manager:
    targetRevision: v1.19.2 # renovate:helm depName=cert-manager registryUrl=https://charts.jetstack.io
    configHelmChart:
      enabled: false
  cilium:
    targetRevision: 1.18.5 # renovate:helm depName=cilium registryUrl=https://helm.cilium.io
    configHelmChart:
      enabled: true
  clickhouse-operator:
    targetRevision: 0.25.5 # renovate:helm depName=altinity-clickhouse-operator registryUrl=https://helm.altinity.com
    configHelmChart:
      enabled: false
  cloudnative-pg:
    targetRevision: 0.27.0 # renovate:helm depName=cloudnative-pg registryUrl=https://cloudnative-pg.io/charts
    configHelmChart:
      enabled: false
  csi-driver-nfs:
    targetRevision: 4.13.1 # renovate:helm depName=csi-driver-nfs registryUrl=https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    configHelmChart:
      enabled: false
  external-dns:
    targetRevision: 1.20.0 # renovate:helm depName=external-dns registryUrl=https://kubernetes-sigs.github.io/external-dns/
    configHelmChart:
      enabled: true
  external-secrets:
    targetRevision: 1.2.1 # renovate:helm depName=external-secrets registryUrl=https://charts.external-secrets.io
    configHelmChart:
      enabled: false
  # gpu-operator:
  #   targetRevision: 25.10.1 # renovate:helm depName=gpu-operator registryUrl=https://helm.ngc.nvidia.com/nvidia
  #   configHelmChart:
  #     enabled: false
  grafana:
    targetRevision: "5.21.4" # renovate:helm depName=grafana-operator registryUrl=https://grafana.github.io/helm-charts
    configHelmChart:
      enabled: true
  kube-prometheus-stack:
    targetRevision: 81.2.0 # renovate:helm depName=kube-prometheus-stack registryUrl=https://prometheus-community.github.io/helm-charts
    configHelmChart:
      enabled: true
  loki:
    targetRevision: 6.49.0 # renovate:helm depName=loki registryUrl=https://grafana.github.io/helm-charts
    configHelmChart:
      enabled: false
  nfs-subdir-external-provisioner:
    targetRevision: 4.0.18 # renovate:helm depName=nfs-subdir-external-provisioner registryUrl=https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    configHelmChart:
      enabled: false
  rook-ceph:
    targetRevision: 1.18.6 # renovate:helm depName=rook-ceph registryUrl=https://charts.rook.io/release
    configHelmChart:
      enabled: false
  rook-ceph-cluster:
    targetRevision: 1.18.6 # renovate:helm depName=rook-ceph-cluster registryUrl=https://charts.rook.io/release
    configHelmChart:
      enabled: true
  tempo:
    targetRevision: 1.24.3 # renovate:helm depName=tempo registryUrl=https://grafana.github.io/helm-charts
    configHelmChart:
      enabled: true
  thanos:
    targetRevision: 17.3.1 # renovate:helm depName=thanos registryUrl=oci://registry-1.docker.io/bitnamicharts
    configHelmChart:
      enabled: false
  tailscale-operator:
    targetRevision: 1.92.5 # renovate:helm depName=tailscale-operator registryUrl=https://pkgs.tailscale.com/helmcharts
    configHelmChart:
      enabled: true
  # velero:
  #   targetRevision: 11.3.2 # renovate:helm depName=velero registryUrl=https://vmware-tanzu.github.io/helm-charts/
  #   configHelmChart:
  #     enabled: true
