instance: omni-local

projects:
  workloads:
    enabled: false

apps:
  alloy:
    targetRevision: 1.4.0 # renovate:helm depName=alloy registryUrl=https://grafana.github.io/helm-charts
    configHelmChart:
      enabled: false
  argocd:
    targetRevision: 9.1.3 # renovate:helm depName=argo-cd registryUrl=https://argoproj.github.io/argo-helm
    configHelmChart:
      enabled: false
  cert-manager:
    targetRevision: 1.19.1 # renovate:helm depName=cert-manager registryUrl=https://charts.jetstack.io
    configHelmChart:
      enabled: false
  cilium:
    targetRevision: 1.18.3 # renovate:helm depName=cilium registryUrl=https://helm.cilium.io
    configHelmChart:
      enabled: true
  external-secrets:
    targetRevision: 0.20.4 # renovate:helm depName=external-secrets registryUrl=https://charts.external-secrets.io
    configHelmChart:
      enabled: false
  grafana:
    targetRevision: "v5.20.0" # renovate:helm depName=grafana-operator registryUrl=https://grafana.github.io/helm-charts
    configHelmChart:
      enabled: true
  internal-ingress-nginx:
    targetRevision: 4.14.0 # renovate:helm depName=ingress-nginx registryUrl=https://kubernetes.github.io/ingress-nginx
    configHelmChart:
      enabled: false
  kube-prometheus-stack:
    targetRevision: 78.5.0 # renovate:helm depName=kube-prometheus-stack registryUrl=https://prometheus-community.github.io/helm-charts
    configHelmChart:
      enabled: true
  local-path-provisioner:
    targetRevision: HEAD
    configHelmChart:
      enabled: false
  loki:
    targetRevision: 6.44.0 # renovate:helm depName=loki registryUrl=https://grafana.github.io/helm-charts
    configHelmChart:
      enabled: false
  omni-bmip:
    targetRevision: HEAD
    configHelmChart:
      enabled: false
  omni:
    targetRevision: HEAD
    configHelmChart:
      enabled: false
  twingate-connector:
    targetRevision: 0.1.31 # renovate:helm depName=connector registryUrl=https://twingate.github.io/helm-charts
    configHelmChart:
      enabled: true
