instance: omni-local

projects:
  workloads:
    enabled: false

apps:
  alloy:
    targetRevision: 1.6.0 # renovate:helm depName=alloy registryUrl=https://grafana.github.io/helm-charts
    configHelmChart:
      enabled: false
  argocd:
    targetRevision: 9.1.5 # renovate:helm depName=argo-cd registryUrl=https://argoproj.github.io/argo-helm
    configHelmChart:
      enabled: false
  cert-manager:
    targetRevision: v1.19.2 # renovate:helm depName=cert-manager registryUrl=https://charts.jetstack.io
    configHelmChart:
      enabled: false
  cilium:
    targetRevision: 1.18.5 # renovate:helm depName=cilium registryUrl=https://helm.cilium.io
    configHelmChart:
      enabled: true
  csi-driver-nfs:
    targetRevision: 4.13.1 # renovate:helm depName=csi-driver-nfs registryUrl=https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    configHelmChart:
      enabled: false
  external-secrets:
    targetRevision: 2.0.0 # renovate:helm depName=external-secrets registryUrl=https://charts.external-secrets.io
    configHelmChart:
      enabled: false
  grafana:
    targetRevision: "5.21.4" # renovate:helm depName=grafana-operator registryUrl=https://grafana.github.io/helm-charts
    configHelmChart:
      enabled: true
  internal-ingress-nginx:
    targetRevision: 4.14.3 # renovate:helm depName=ingress-nginx registryUrl=https://kubernetes.github.io/ingress-nginx
    configHelmChart:
      enabled: false
  kube-prometheus-stack:
    targetRevision: 81.6.9 # renovate:helm depName=kube-prometheus-stack registryUrl=https://prometheus-community.github.io/helm-charts
    configHelmChart:
      enabled: true
  local-path-provisioner:
    targetRevision: HEAD
    configHelmChart:
      enabled: false
  loki:
    targetRevision: 6.53.0 # renovate:helm depName=loki registryUrl=https://grafana.github.io/helm-charts
    configHelmChart:
      enabled: false
  omni-bmip:
    targetRevision: HEAD
    configHelmChart:
      enabled: false
  omni:
    targetRevision: HEAD
    configHelmChart:
      enabled: false
  tailscale-operator:
    targetRevision: 1.92.5 # renovate:helm depName=tailscale-operator registryUrl=https://pkgs.tailscale.com/helmcharts
    configHelmChart:
      enabled: true
