operator:
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 100Mi

secret:
  create: false

serviceMonitor:
  enabled: true

dashboards:
  enabled: true
  additionalLabels:
    app: grafana

additionalResources:
  - |
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: clickhouse-operator-es
      namespace: clickhouse-operator
    spec:
      refreshInterval: 1h
      secretStoreRef:
        name: infisical-secret-store
        kind: ClusterSecretStore
      target:
        name: clickhouse-operator
      data:
        - secretKey: username
          remoteRef:
            key: /clickhouse-operator/ZENDO_CLICKHOUSE_OPERATOR_USERNAME
        - secretKey: password
          remoteRef:
            key: /clickhouse-operator/ZENDO_CLICKHOUSE_OPERATOR_PASSWORD
